# Generated by Django 2.0.2 on 2018-03-06 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_cat_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='cat',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
